on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - run: cargo fmt --manifest-path server/Cargo.toml
      - run: cargo check --manifest-path server/Cargo.toml
      - run: cargo test --manifest-path server/Cargo.toml
      - uses: EndBug/add-and-commit@v7
        with:
          user_name: Reformatting Bot
          user_email: maxbmhlee@gmail.com
          message: Reformatted Code
